version = 0.1
[default.deploy.parameters]
stack_name = "openai-lambda-layer-sam"
resolve_s3 = true
s3_prefix = "openai-lambda-layer-sam"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "LayerName=\"openai-layer\" PythonVersion=\"python3.12\""
image_repositories = []
